name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          bubblewrap init --manifest https://raw.githubusercontent.com/${{ github.repository }}/main/manifest.json
          yes "" | bubblewrap update
          bubblewrap build --skipPwaValidation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ranked-Draft-Simulator-APK
          path: |
            **/*.apk
